pub const MAXIMUM_NUM_READS_PER_OPCODE: usize = 3;
pub const MAXIMUM_NUM_WRITES_PER_OPCODE: usize = MAXIMUM_NUM_READS_PER_OPCODE - 1;
pub const MAXIMUM_NUM_ACCESSES_PER_OPCODE: usize = MAXIMUM_NUM_READS_PER_OPCODE + MAXIMUM_NUM_WRITES_PER_OPCODE;